### ISSUE TITLE
global: remove dependency on flask-login

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-i18n#83] opened 2020-05-03 15:11 UTC
[This part](https://github.com/inveniosoftware/invenio-i18n/blob/master/invenio_i18n/selectors.py#L52-L59) should be refactored so that Invenio-I18N does not depend on Flask-Login/Invenio-Accounts

**Comment by chriz-uniba** [comment] 2023-08-17 07:06
Am I right, that the issue is/was the `current_user` in this method
https://github.com/inveniosoftware/invenio-i18n/blob/287849c1dd52904cbb7c7da4e6da469b603a2dfe/invenio_i18n/selectors.py#L54-L65

Is this issue still an issue?
I think @rekt-hard was currently mentioning/working on language preferences for v12 - is this related?

**Comment by rekt-hard** [comment] 2023-08-23 08:33
afaik, in previous versions, the locale was set on the user directly (hence the `language_user_key` which could be configured). Currently, the locale is stored in the `user_preferences`.

In general, I am not sure if the whole part regarding the user shall be removed or we should just refactor it to make it work with the current implementation.

**Comment by chriz-uniba** [comment] 2023-09-21 07:11
Can we figure out, who needs to be involved to get a decision here?
@rekt-hard @lnielsen

**Comment by chriz-uniba** [comment] 2024-03-21 10:48
discussed with @lnielsen 
- we close it and see whether it pops up again.

**Closed** 2024-03-21 10:49 UTC
